artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/PriyanshuDey23/Hate-Speech-Classification/raw/main/Data/Hate_dataset.zip
  local_data_file: artifacts/data_ingestion/hate.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: artifacts\data_ingestion\imbalanced_data.csv,artifacts\data_ingestion\raw_data.csv