artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/PriyanshuDey23/Hate-Speech-Classification/raw/main/Data/Hate_dataset.zip
  local_data_file: artifacts/data_ingestion/hate.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: artifacts\data_ingestion\imbalanced_data.csv,artifacts\data_ingestion\raw_data.csv


data_transformation:
  root_dir : artifacts/data_transformation
  Transformed_filename : artifacts/data_transformation/final.csv
  Data_dir : "data"
  Id : 'id'
  Axis : 1
  Inplace : True
  Drop_Columns : ['Unnamed: 0','count','hate_speech','offensive_language','neither']
  Class : 'class'
  Label : 'label'
  Tweet : 'tweet'


model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_path: artifacts/model_trainer/model/model.h5
  x_test_data_path: artifacts/model_trainer/x_test.csv
  x_train_data_path: artifacts/model_trainer/x_train.csv
  y_test_data_path: artifacts/model_trainer/y_test.csv