artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/PriyanshuDey23/Hate-Speech-Classification/raw/main/Data/Hate_dataset.zip
  local_data_file: artifacts/data_ingestion/hate.zip
  unzip_dir: artifacts/data_ingestion